version: '3.7'
services:
  app:
    container_name: blank_php
    build:
      context: docker/php
      dockerfile: Dockerfile
    init: true
    tty: true
    restart: unless-stopped
    volumes:
      - .:/var/www:delegated
    networks:
      - in_net
    ports:
    - ${DEV_APP_PORT}:80

networks:
  in_net:
    driver: "bridge"
volumes:
  dbdata:
    driver: local
